### ISSUE TITLE
Not work

### ISSUE THREAD

**Issue by xcitv** [sabbiriptv/TATA-PLAY#1]
The link not work
Please check it

**Comment by sabbiriptv** [comment]
Check Now

**Comment by Jaysarna** [comment]
still not working

**Comment by xcitv** [comment]
It cant play because dont have drm key
Do you have just by hls so no neeed drm key to play it

**Comment by xcitv** [comment]
It works
But how can i play it without vpn??

**Comment by sabbiriptv** [comment]
You Have To Be In India To Play This M3U, So If You Live **Outside India VPN Is Must Needed**

**Comment by xcitv** [comment]
Drm key false
