### ISSUE TITLE
Not working in Tivimate.

### ISSUE THREAD

**Issue by Dhan590** [sabbiriptv/TATA-PLAY#4]
![Screenshot_20230520-160459_TiviMate](https://github.com/sabbiriptv/TATA-PLAY/assets/79129522/599b3605-9a48-42c2-bf0e-ed68f693c4b3)

**Comment by Kedharnadh** [comment]
![Screenshot_2023-05-21-12-03-23-79_ac2214a033de173e2b109aa5e2fffc90](https://github.com/sabbiriptv/TATA-PLAY/assets/8991265/d4e5f62e-28b8-4529-89ed-10692eeb75bd)
Not playing on OTT navigator as well

**Comment by sabbiriptv** [comment]
Check Again

**Comment by Kedharnadh** [comment]
It is working now ✌🏻

**Comment by sabbiriptv** [comment]
Enjoy!

**Comment by Kedharnadh** [comment]
It is not working again bro, I think there might be some issue with tokens 🤷🏻‍♂️

**Comment by Kedharnadh** [comment]
> > Enjoy!
> 
> Yeah, not working in Tivimate either.

Its is working now

**Comment by sabbiriptv** [comment]
@Dhan590 @Kedharnadh,
I might add an automated script for updating M3U's periodically (if my exam goes well 😀)

**Comment by Dhan590** [comment]
> @Dhan590, I don't have any active TATAPLAY subscription, that's the problem can you please DM me on discord? SabbirHasan#6976 or TG https://t.me/abuwahabis

Messaged you on TG, couldn't find your Discord.
