### ISSUE TITLE
Unable to play 

### ISSUE THREAD

**Issue by Kedharnadh** [sabbiriptv/TATA-PLAY#5]
Unable to play channels bro. Facing 500 error
![Screenshot_2023-06-04-20-14-55-58_ac2214a033de173e2b109aa5e2fffc90](https://github.com/sabbiriptv/TATA-PLAY/assets/8991265/b3f2b08e-26f9-4cb3-b1d9-f01b493388d5)

**Comment by sabbiriptv** [comment]
Sorry,
Did a silly mistake in hurry 😓!
It should be okay now ✔

**Comment by Kedharnadh** [comment]
It is working now, thanks for your great work bro
