### ISSUE TITLE
No channel is working 

### ISSUE THREAD

**Issue by lavish440** [sabbiriptv/TATA-PLAY#6]
I tried the playlist in Kodi, VLC and Televizo but not even a single channel is playing anywhere.

**Comment by sabbiriptv** [comment]
Updated Check Now!

**Comment by lavish440** [comment]
Still not working for me. I'm still unable to 0lay any channel. Kodi fails with the logs :
`AddOnLog: inputstream.adaptive: No decrypter found for encrypted stream`

**Comment by sabbiriptv** [comment]
**Install the Widevine CDM (Content Decryption Module) library:**

1. Open Kodi and navigate to "Add-ons" in the main menu.
2. Select "Download" in the Add-ons screen.
3. Search for "Widevine" and install the appropriate Widevine CDM add-on for your platform (Windows, macOS, Linux, etc.).

**Configure inputstream.adaptive add-on:**

1. Open Kodi and go to "Add-ons" in the main menu.
2. Select "My add-ons" and scroll down to find "InputStream Adaptive."
3. Click on it to open the add-on settings.
4. Enable the "DRM Support" option and set it to "Widevine."

If it still not works then try to use <strong>Tivimate</strong> or <strong>OTT Navigator</strong>

**Comment by lavish440** [comment]
There is no Widevine addon for Kodi on my Android TV.

**Comment by lavish440** [comment]
I tried using it on OTT Navigator on my phone and now it is working but I want to use it on Kodi on my Android TV.

**Comment by lavish440** [comment]
After researching I found it in my Kodi installation 
![screencap](https://github.com/sabbiriptv/TATA-PLAY/assets/64689132/c2b33f22-f5e6-4ae9-a2dc-78af4b81f61c)

**Comment by lavish440** [comment]
Tried using it on Linux but it also didn't work there. It is still not playing with the same error
`AddOnLog: inputstream.adaptive: No decrypter found for encrypted stream`
